=pod

=head1 NAME

Meepo - Compile HTML::Template templates into Perl or JavaScript code

=head1 SYNOPSIS

General usage

	use Meepo;

	my $coderef = Meepo::poof($template);

	die $@ if $@;

	print (eval $$coderef)->($parameters);

Build context

	$Meepo::context->{'builder'} = 'JavaScript';
	$coderef = Meepo::poof($template);

Optional parameters

	$coderef = Meepo::poof($template => {
		builder => 'JavaScript',
		inc => ['/home/user/templates', '../templates'],
	});
	
Object notation

	$coderef = Meepo->poof({
		source => $template,
	});


=head1 DESCRIPTION

This module parses template files and creates parse tree. Depending on selected builder Perl or JavaScript code is generated.

Generated code can be compiled to anonymous function and run as needed.

=head1 PERFORMANCE

Latest measurements showed that Meepo's Perl clone is slightly faster than HTML::Template::Pro. JavaScript clone performance will 
be measured in near future.

=head1 COPYRIGHT & LICENSE

Copyright 2012 Alexander Nazarov, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut
