=pod

=head1 NAME

Template::Meepo - Compile L<HTML::Template> templates into Perl or JavaScript code

=head1 SYNOPSIS

General usage

	use Template::Meepo;

	my $coderef = Template::Meepo::poof($template);

	die $@ if $@;

	print (eval $$coderef)->($parameters);

Build context

	$Template::Meepo::context->{'builder'} = 'JavaScript';
	$coderef = Template::Meepo::poof($template);

Optional parameters

	$coderef = Template::Meepo::poof($template => {
		builder => 'JavaScript',
		inc => ['/home/user/templates', '../templates'],
	});
	
Object notation

	$coderef = Template::Meepo->poof({
		source => $template,
	});


=head1 DESCRIPTION

This module parses template files and creates parse tree. Depending on selected builder Perl or JavaScript code is generated.

Generated code can be compiled to anonymous function and run as needed.

=head1 SEE ALSO

L<HTML::Template::Pro>, L<HTML::Template>

=head1 COPYRIGHT & LICENSE

Copyright 2012 Alexander Nazarov, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut
